### ISSUE TITLE
Error on all meteor builds

### ISSUE THREAD

**Issue by andrerfneves** [sungwoncho/meteor-stat#1]
Neat package. However it crashes in all of my meteor builds/apps with or without a gitignore file. Tried --help, -h and everythign crashes.

master ● > mstat
/usr/local/lib/node_modules/meteor-stat/lib/cli.js:12
  .option('-i, --gitignore [path]', `Specify the path to .gitignore file. [${d
                                    ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-stat/bin/mstat:3:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by sungwoncho** [comment]
Thanks for filing.

The issue is that your version of node is not supporting es6 (notice the template string). Try upgrading node to version later than 4. I will take a PR for backward support for node.

**Comment by andrerfneves** [comment]
Oh got it. No worries. I'll figure this out. Cheers
