### ISSUE TITLE
SyntaxError after normal installation

### ISSUE THREAD

**Issue by afang** [sungwoncho/meteor-stat#2]
```
/usr/local/lib/node_modules/meteor-stat/lib/cli.js:12
  .option('-i, --gitignore [path]', `Specify the path to .gitignore file. [${d
                                    ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-stat/bin/mstat:3:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
after running `mstat`

**Comment by sungwoncho** [comment]
Please see [README](https://github.com/sungwoncho/meteor-stat#node-dependency).
